### ISSUE TITLE
안녕하세요, 집단 지성 프로젝트 관련해 여쭤볼 게 있습니다.

### ISSUE THREAD

**Issue by veatoriche** [encrypted-def/basic-algo-lecture#2]
[유일한 이모지가 있는 글](https://blog.encrypted.gg/980?category=773649) 을 보고 Issue 남기게 되었습니다.

제가 바킹독님 강의를 보면서 문제집을 정주행 하고있는데, 요즘 Java에 관심이 생기다 보니, Java로 문제집을 풀게 되었는데, 집단 지성 프로젝트에 제가 작성한 코드나 다른 분의 코드를 공유하거나 공유하기 위한 규정이 생겼으면 좋겠다는 생각이 들었습니다!

그래서, 혹시 문제집 집단지성 프로젝트에 Java로 작성된 소스코드를 PR하거나 관련 규정을 제안드려도 괜찮을까요?

아무쪼록 좋은 강의 공유해주셔서 감사합니다. 새 취미가 생겨서 요즘 기분이 좋네요 😃

**Comment by encrypted-def** [comment]
자바, 파이썬의 경우도 생각은 해봤는데 제가 두 언어로 ps를 잘 안하다보니 공통된 컨벤션을 정하기가 좀 애매했습니다.  또 컨벤션을 어찌저찌 정해서 PR을 받는다고 해도 그 코드가 '좋은' 코드인지 제가 판단하기 좀 어려울 것 같았습니다. 그러면 결국 보내주신 코드를 거의 그대로 올리게 될텐데 그런 상황을 생각해보면 그냥 `BOJ 1000`과 같이 검색해서 코드를 찾는 것과 별 차이가 없다고 생각했습니다.

그래서 자바, 파이썬을 따로 PR 받을 생각은 없지만 따로 repository를 만들어서 자바/파이썬 코드를 관리해주신다면 자바, 파이썬 이용자들에게 큰 도움이 될 것 같습니다.

**Comment by veatoriche** [comment]
@encrypted-def // 빠른 답변 감사드립니다. 답변 주신 점 읽어보니, 저장소 관리자, 문제집 출제자로서 퀄리티 관리가 애매하고 힘든 것이란 점을 제가 인지하지 못한 것 같네요 🙏 

제 개인 저장소에 저장해두면서 좀 더 진행하다 C++로 갈아타게 되면 적극적으로 기여하겠습니다.

감사드립니다 :)
