### ISSUE TITLE
9375.cpp가 0x12에도 존재합니다.

### ISSUE THREAD

**Issue by hehehwang** [encrypted-def/basic-algo-lecture#213]
안녕하세요 바킹독님
9375 [패션왕 신해빈](https://www.acmicpc.net/problem/9375)문제는 0x15 해시 문제로 등재가 되어있는데,
0x12 수학 단원에도 (문제집 등재 없이)[파일](https://github.com/encrypted-def/basic-algo-lecture/blob/master/0x12/solutions/9375.cpp)이 올라가있습니다.

관련해서 수정 부탁드립니다.

**Comment by encrypted-def** [comment]
삭제했습니다!
