### ISSUE TITLE
BFS 단원 문제집 2146번의 첨부하신 링크에서 에러가 납니다.

### ISSUE THREAD

**Issue by penguin0000000000** [encrypted-def/basic-algo-lecture#435]
BFS를 2번만 해서 푸는 O(N^2) 풀이의 설명 링크가
http://www.secmem.org/blog/2019/03/07/코딩테스트-대비-특강/
으로 되어 있는데 404에러가 납니다. 확인 부탁드립니다.

**Comment by encrypted-def** [comment]
수정했습니다 감사합니다!

**Comment by encrypted-def** [comment]
이제 발견했네요ㅎㅎ,,, 정답 코드도 수정했습니다!
