### ISSUE TITLE
바킹독님! 질문드립니다!

### ISSUE THREAD

**Issue by SungKweon** [encrypted-def/basic-algo-lecture#72]
안녕하세요!
깃헙, 백준 초보 입문자입니당
이렇게 깃헙에서 질문을 드리는게 맞는지 잘 모르겠지만 ㅎㅎ

'집단지성 프로젝트'를 참여하고 있는 취준생인데용
**백준 10807문제**에 대한 코드를 VScode에서 돌렸을 경우에는 잘 돌아가는데 비해,
백준에 제출했을 경우, 틀렸다고 뜨네요..ㅠㅠ

혹시 확인 가능하시면, 답변 부탁드리겠습니당
아래 백준 제출 링크 같이 보내드립니다!

백준 제출 링크: http://boj.kr/d52171ee307a4ba384497ecd2d7c1aa1

**Comment by SungKweon** [comment]
백준 제출 링크 다시 보내드립니당
http://boj.kr/d52171ee307a4ba384497ecd2d7c1aa1

**Comment by encrypted-def** [comment]
반례는

```
1
0
0
```
입니다. 반례를 돌려보면 바로 감이 올 것 같은데, range-based for 사용에 주의할 필요가 있습니다.

개인적으로는 이 문제의 경우 v의 개수만 파악하면 되니 굳이 freq 배열을 쓰기 보다는 그냥 for문을 돌면서 개수를 세는게 더 바람직하다고 생각합니다. 앞으로 질문은 해당 강의의 블로그 글이나 유튜브 영상의 댓글로 달아주시면 다른 분들이 쉽게 참고할 수 있어서 좋을 것 같습니다!

**Comment by SungKweon** [comment]
빠른 답변 감사합니다!
덕분에 잘 해결했습니다 ^^
