### ISSUE TITLE
문제집 풀이 집단 지성의 컨벤션중 [규칙14]에 대해 건의 드리고 싶은 부분이 있습니다.

### ISSUE THREAD

**Issue by unluckyjung** [encrypted-def/basic-algo-lecture#9]
[문제집 풀이 집단지성](https://github.com/encrypted-def/basic-algo-lecture/blob/master/solution-request.md) 의 컨벤션중 

> [규칙14] 구조체 혹은 클래스를 사용하지 않아야 합니다.

라는 부분이 있습니다.
의도하신바는 ps 풀이인 만큼, 문제 해결을 위한 절차지향적인 풀이를 의도 하시고 `객체지향적으로 구현한 코드는 지양` 하는것으로 이해를 했는데

**구조체를 사용하지 않아야 합니다** 부분은 제거되어도 괜찮지 않을까 싶어 이슈 남깁니다.

예시로 과거에 제가 푼 문제인 [나무 제테크](http://boj.kr/230e5ed3717347b3b4ab28c322d445bb) 이나 [낚시왕](http://boj.kr/6f3f4a9b68e64291bd0db948ebe3e562), [Gaaaaaaaaaarden](https://www.acmicpc.net/source/share/66f7ee9d1e374b94b216e5b16a3a14c1)을 보면
정보를 3개이상 담을때는 tuple 보다는 struct를 이용했습니다.

**개인적인 생각** 으로는, 시뮬레이션 문제의 경우 정보를 여러개 담고 보관해야 하는 경우가 많은데
`pair<pair<int,int>, int>` 이런 형태이거나 tuple보다는 
가독성을 위해서 네이밍이 붙은 구조체를 사용하는것 정도는 괜찮다고 생각이 들어, 건의 드립니다.

**Comment by encrypted-def** [comment]
구조체를 쓰는게 절대 나쁜 습관이라는 의미는 아닙니다. 다만 제가 PS를 할 때에는 대소 관계가 미리 잘 정의되어 있다는 점이 좋아서 구조체 대신 pair와 tuple을 쓰는 것을 선호해서 저 규칙을 뒀습니다. 저 규칙이 그렇게 좋은 규칙이라고는 볼 수 없지만 저는 가능하면 등록해주시는 코드들이 제가 짠 코드와 느낌이 거의 비슷하길 원해서 저런 규칙을 둔 점 양해 부탁드립니다.

**Comment by unluckyjung** [comment]
확인했습니다!!
